---
name: Publish review app

on:
  workflow_dispatch:
    inputs:
     refName:
       description: "Ref name"
       required: true
     dst:
       description: "Where to deploy"
       required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.refName }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: Build
        run: npm run build
        env:
          REACT_APP_BACKEND_URL: http://${{ github.event.inputs.refName }}.${{ secrets.API_URL }}
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Setup SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Copy build to the server
        run: |
          ssh $SSH_USER@$SSH_HOST "mkdir -p ~/app/${{ github.event.inputs.refName }}/public"
          rsync -ravz build/* $SSH_USER@$SSH_HOST:~/app/${{ github.event.inputs.refName }}/public/
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
